# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
      username: admin
      password: admin
      role: Admin

  connections:
    - conn_id: "my_postgres_id"
      conn_type: postgres
      host: postgres
      schema: postgres
      login: postgres
      password: postgres
      port: 5432
